# Generated by Django 4.1.3 on 2022-12-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(choices=[('mercedez', 'MERCEDEZ'), ('honda', 'HONDA'), ('toyota', 'TOYOTA'), ('bmw', 'BMW'), ('ferari', 'FERARI'), ('ford', 'FORD'), ('range rover', 'RANGE ROVER'), ('bentley', 'BENTLEY'), ('maclauren', 'MACLAUREN')], max_length=50)),
                ('year', models.CharField(choices=[('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4)),
                ('status', models.CharField(choices=[('new', 'New'), ('nused', 'Nigerian Used'), ('fused', 'Foreign Used')], max_length=20)),
                ('colour', models.CharField(choices=[('white', 'WHITE'), ('black', 'BLACK'), ('yellow', 'YELLOW'), ('pink', 'PINK'), ('brown', 'BROWN'), ('red', 'RED'), ('green', 'GREEN'), ('blue', 'BLUE'), ('peach', 'PEACH')], max_length=8)),
                ('price', models.CharField(max_length=50)),
                ('number_available', models.PositiveIntegerField()),
                ('comments', models.TextField(max_length=300)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
